# PtahCore — ASAP7 config for chip_top (Phase 7d): the whole
# accelerator. The 32×32 array enters as ONE hard macro (the fifth
# GDS), SMEM as 16 fakeram7_256x256 1RW macros (smem_phys.sv), and the
# traveling clock is generated by the dont_touch spine buffer chains
# (clk_spine port → ptah_clkbuf/BUFx24 instances — CHIP_SPEC §1).
#
# Run: flow/harden_chip.sh (checks the grid macro artifacts first).

export DESIGN_NICKNAME = chip_top
export DESIGN_NAME     = chip_top
export PLATFORM        = asap7

# Chip-side RTL only. mac_grid (and everything inside it) and the
# fakerams resolve from their liberty models — riscv32i-mock-sram
# pattern, no BLOCKS nickname dance, no re-hardening.
export VERILOG_FILES = \
  $(PTAHCORE)/rtl/fp8_decode.sv $(PTAHCORE)/rtl/fp8_encode.sv \
  $(PTAHCORE)/rtl/ptah_clkbuf.sv $(PTAHCORE)/rtl/clk_spine.sv \
  $(PTAHCORE)/rtl/mac_array.sv $(PTAHCORE)/rtl/mma_unit.sv \
  $(PTAHCORE)/rtl/smem_phys.sv $(PTAHCORE)/rtl/barrier.sv \
  $(PTAHCORE)/rtl/load.sv $(PTAHCORE)/rtl/store.sv \
  $(PTAHCORE)/rtl/cmdproc.sv $(PTAHCORE)/rtl/chip_top.sv
# GRID_MACRO: instantiate mac_grid parameterless so the liberty-derived
# module (bus pins, no parameters) resolves it directly.
export VERILOG_DEFINES = -DSYNTHESIS -DGRID_MACRO

# The 256×160 CMD FIFO (40,960 b) + REPEAT buffer synthesize to flops
# in v1 (≈41 k DFF, affordable in the west strip; a regfile macro is a
# recorded improvement). Default cap is 4,096 bits.
export SYNTH_MEMORY_MAX_BITS = 65536

export SDC_FILE = $(PTAHCORE)/flow/designs/asap7/chip_top/constraint.sdc

# Design-local PDN: the grid macro's power pins are its own M6 straps
# under an exact-OBS M7 (flow/exact_obs_lef.py) — the platform macro
# grids only know the fakeram M4→M5 contract (PDN-0232). Also powers
# the dont_touch spine buffers (ODB-0383). See pdn.tcl header.
export PDN_TCL = $(PTAHCORE)/flow/designs/asap7/chip_top/pdn.tcl

# Hard macros: the array (our fifth GDS) + the platform SRAMs.
# FakeRAM2.0 is a black-box generator — no GDS internals exist; the
# merged chip GDS carries the SRAM outlines only (recorded limitation,
# the same class autogpu shipped with).
export ADDITIONAL_LEFS += $(PLATFORM_DIR)/lef/fakeram7_256x256.lef \
  $(WORK_HOME)/results/asap7/mac_grid/base/mac_grid.lef
export ADDITIONAL_LIBS += $(PLATFORM_DIR)/lib/NLDM/fakeram7_256x256.lib \
  $(WORK_HOME)/results/asap7/mac_grid/base/mac_grid_typ.lib
export ADDITIONAL_GDS  += $(WORK_HOME)/results/asap7/mac_grid/base/6_final.gds

# Floorplan (gen_floorplan.py — regenerate after geometry changes):
# grid macro at the south-east, L-strip west (logic + SRAM column +
# spine) and north (B launch) — CHIP_SPEC §3.
export DIE_AREA  = 0 0 1674.432 1583.280
export CORE_AREA = 2.160 2.160 1672.272 1581.120
export MACRO_PLACEMENT_TCL = $(PTAHCORE)/flow/designs/asap7/chip_top/macro_place.tcl
export IO_CONSTRAINTS = $(PTAHCORE)/flow/designs/asap7/chip_top/io_constraints.tcl
export MACRO_PLACE_HALO = 2 2
export PLACE_DENSITY = 0.40

# House style (see mac_grid/config.mk for each lesson).
export LEC_CHECK = 0
export HOLD_SLACK_MARGIN = 15
export SETUP_SLACK_MARGIN = 100
export SLEW_MARGIN = 30
export GLOBAL_ROUTE_ARGS = -congestion_iterations 2 -allow_congestion -congestion_report_iter_step 1 -verbose
