# GENERATED by gen_constraints.py — do not hand-edit.
# The chip-level clock contract (CHIP_SPEC §1-2, HARDENING.md 7d-3).
# Units: PICOSECONDS.

set clk_period 4000

# Two source clocks: clk (logic, CTS trees it) and clk_spine (the
# deliberate traveling-clock backbone; clk_s_tap is its CTS-treed
# stage-A fanout — config.mk CTS_ARGS).
create_clock -name clk       -period $clk_period [get_ports clk]
create_clock -name clk_spine -period $clk_period [get_ports clk_spine]
set_clock_uncertainty 100 [get_clocks clk]
set_clock_uncertainty 100 [get_clocks clk_spine]

# The spine BACKBONE is deliberate structure — CTS must not balance
# it, the resizer must not size it (matched by instance path, so the
# launch tap drivers and CTS buffers stay free; HARDENING ODB-0373).
set_dont_touch [get_cells -hierarchical -filter "name =~ *u_spine_*"]
set_dont_touch [get_nets  -hierarchical -filter "name =~ *u_spine_*"]

# ── Stage-B launch clocks: per-tap generated clocks carrying the
# designed stagger as source latency, NOT propagated (the contract
# phase replaces the un-treed-net phantom RC). Anchored on each
# launch buffer's output net driver — hierarchy-robust.
set _p [get_pins -of_objects [get_nets {clk_lw_buf[0]}] -filter {direction == output}]
create_generated_clock -name lw_0 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1445.00 [get_clocks lw_0]
set_clock_uncertainty 100 [get_clocks lw_0]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[1]}] -filter {direction == output}]
create_generated_clock -name lw_1 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1530.00 [get_clocks lw_1]
set_clock_uncertainty 100 [get_clocks lw_1]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[2]}] -filter {direction == output}]
create_generated_clock -name lw_2 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1615.00 [get_clocks lw_2]
set_clock_uncertainty 100 [get_clocks lw_2]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[3]}] -filter {direction == output}]
create_generated_clock -name lw_3 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1700.00 [get_clocks lw_3]
set_clock_uncertainty 100 [get_clocks lw_3]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[4]}] -filter {direction == output}]
create_generated_clock -name lw_4 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1785.00 [get_clocks lw_4]
set_clock_uncertainty 100 [get_clocks lw_4]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[5]}] -filter {direction == output}]
create_generated_clock -name lw_5 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1870.00 [get_clocks lw_5]
set_clock_uncertainty 100 [get_clocks lw_5]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[6]}] -filter {direction == output}]
create_generated_clock -name lw_6 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1955.00 [get_clocks lw_6]
set_clock_uncertainty 100 [get_clocks lw_6]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[7]}] -filter {direction == output}]
create_generated_clock -name lw_7 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2040.00 [get_clocks lw_7]
set_clock_uncertainty 100 [get_clocks lw_7]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[8]}] -filter {direction == output}]
create_generated_clock -name lw_8 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2125.00 [get_clocks lw_8]
set_clock_uncertainty 100 [get_clocks lw_8]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[9]}] -filter {direction == output}]
create_generated_clock -name lw_9 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2210.00 [get_clocks lw_9]
set_clock_uncertainty 100 [get_clocks lw_9]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[10]}] -filter {direction == output}]
create_generated_clock -name lw_10 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2295.00 [get_clocks lw_10]
set_clock_uncertainty 100 [get_clocks lw_10]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[11]}] -filter {direction == output}]
create_generated_clock -name lw_11 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2380.00 [get_clocks lw_11]
set_clock_uncertainty 100 [get_clocks lw_11]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[12]}] -filter {direction == output}]
create_generated_clock -name lw_12 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2465.00 [get_clocks lw_12]
set_clock_uncertainty 100 [get_clocks lw_12]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[13]}] -filter {direction == output}]
create_generated_clock -name lw_13 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2550.00 [get_clocks lw_13]
set_clock_uncertainty 100 [get_clocks lw_13]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[14]}] -filter {direction == output}]
create_generated_clock -name lw_14 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2635.00 [get_clocks lw_14]
set_clock_uncertainty 100 [get_clocks lw_14]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[15]}] -filter {direction == output}]
create_generated_clock -name lw_15 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2720.00 [get_clocks lw_15]
set_clock_uncertainty 100 [get_clocks lw_15]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[16]}] -filter {direction == output}]
create_generated_clock -name lw_16 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2805.00 [get_clocks lw_16]
set_clock_uncertainty 100 [get_clocks lw_16]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[17]}] -filter {direction == output}]
create_generated_clock -name lw_17 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2890.00 [get_clocks lw_17]
set_clock_uncertainty 100 [get_clocks lw_17]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[18]}] -filter {direction == output}]
create_generated_clock -name lw_18 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2975.00 [get_clocks lw_18]
set_clock_uncertainty 100 [get_clocks lw_18]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[19]}] -filter {direction == output}]
create_generated_clock -name lw_19 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3060.00 [get_clocks lw_19]
set_clock_uncertainty 100 [get_clocks lw_19]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[20]}] -filter {direction == output}]
create_generated_clock -name lw_20 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3145.00 [get_clocks lw_20]
set_clock_uncertainty 100 [get_clocks lw_20]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[21]}] -filter {direction == output}]
create_generated_clock -name lw_21 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3230.00 [get_clocks lw_21]
set_clock_uncertainty 100 [get_clocks lw_21]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[22]}] -filter {direction == output}]
create_generated_clock -name lw_22 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3315.00 [get_clocks lw_22]
set_clock_uncertainty 100 [get_clocks lw_22]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[23]}] -filter {direction == output}]
create_generated_clock -name lw_23 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3400.00 [get_clocks lw_23]
set_clock_uncertainty 100 [get_clocks lw_23]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[24]}] -filter {direction == output}]
create_generated_clock -name lw_24 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3485.00 [get_clocks lw_24]
set_clock_uncertainty 100 [get_clocks lw_24]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[25]}] -filter {direction == output}]
create_generated_clock -name lw_25 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3570.00 [get_clocks lw_25]
set_clock_uncertainty 100 [get_clocks lw_25]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[26]}] -filter {direction == output}]
create_generated_clock -name lw_26 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3655.00 [get_clocks lw_26]
set_clock_uncertainty 100 [get_clocks lw_26]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[27]}] -filter {direction == output}]
create_generated_clock -name lw_27 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3740.00 [get_clocks lw_27]
set_clock_uncertainty 100 [get_clocks lw_27]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[28]}] -filter {direction == output}]
create_generated_clock -name lw_28 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3825.00 [get_clocks lw_28]
set_clock_uncertainty 100 [get_clocks lw_28]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[29]}] -filter {direction == output}]
create_generated_clock -name lw_29 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3910.00 [get_clocks lw_29]
set_clock_uncertainty 100 [get_clocks lw_29]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[30]}] -filter {direction == output}]
create_generated_clock -name lw_30 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3995.00 [get_clocks lw_30]
set_clock_uncertainty 100 [get_clocks lw_30]
set _p [get_pins -of_objects [get_nets {clk_lw_buf[31]}] -filter {direction == output}]
create_generated_clock -name lw_31 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 4080.00 [get_clocks lw_31]
set_clock_uncertainty 100 [get_clocks lw_31]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[0]}] -filter {direction == output}]
create_generated_clock -name lb_0 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1729.14 [get_clocks lb_0]
set_clock_uncertainty 100 [get_clocks lb_0]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[1]}] -filter {direction == output}]
create_generated_clock -name lb_1 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1811.48 [get_clocks lb_1]
set_clock_uncertainty 100 [get_clocks lb_1]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[2]}] -filter {direction == output}]
create_generated_clock -name lb_2 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1893.82 [get_clocks lb_2]
set_clock_uncertainty 100 [get_clocks lb_2]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[3]}] -filter {direction == output}]
create_generated_clock -name lb_3 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 1976.16 [get_clocks lb_3]
set_clock_uncertainty 100 [get_clocks lb_3]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[4]}] -filter {direction == output}]
create_generated_clock -name lb_4 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2058.50 [get_clocks lb_4]
set_clock_uncertainty 100 [get_clocks lb_4]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[5]}] -filter {direction == output}]
create_generated_clock -name lb_5 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2140.84 [get_clocks lb_5]
set_clock_uncertainty 100 [get_clocks lb_5]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[6]}] -filter {direction == output}]
create_generated_clock -name lb_6 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2223.18 [get_clocks lb_6]
set_clock_uncertainty 100 [get_clocks lb_6]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[7]}] -filter {direction == output}]
create_generated_clock -name lb_7 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2305.52 [get_clocks lb_7]
set_clock_uncertainty 100 [get_clocks lb_7]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[8]}] -filter {direction == output}]
create_generated_clock -name lb_8 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2387.86 [get_clocks lb_8]
set_clock_uncertainty 100 [get_clocks lb_8]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[9]}] -filter {direction == output}]
create_generated_clock -name lb_9 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2470.20 [get_clocks lb_9]
set_clock_uncertainty 100 [get_clocks lb_9]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[10]}] -filter {direction == output}]
create_generated_clock -name lb_10 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2552.54 [get_clocks lb_10]
set_clock_uncertainty 100 [get_clocks lb_10]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[11]}] -filter {direction == output}]
create_generated_clock -name lb_11 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2634.88 [get_clocks lb_11]
set_clock_uncertainty 100 [get_clocks lb_11]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[12]}] -filter {direction == output}]
create_generated_clock -name lb_12 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2717.22 [get_clocks lb_12]
set_clock_uncertainty 100 [get_clocks lb_12]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[13]}] -filter {direction == output}]
create_generated_clock -name lb_13 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2799.56 [get_clocks lb_13]
set_clock_uncertainty 100 [get_clocks lb_13]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[14]}] -filter {direction == output}]
create_generated_clock -name lb_14 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2881.90 [get_clocks lb_14]
set_clock_uncertainty 100 [get_clocks lb_14]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[15]}] -filter {direction == output}]
create_generated_clock -name lb_15 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 2964.24 [get_clocks lb_15]
set_clock_uncertainty 100 [get_clocks lb_15]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[16]}] -filter {direction == output}]
create_generated_clock -name lb_16 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3046.58 [get_clocks lb_16]
set_clock_uncertainty 100 [get_clocks lb_16]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[17]}] -filter {direction == output}]
create_generated_clock -name lb_17 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3128.92 [get_clocks lb_17]
set_clock_uncertainty 100 [get_clocks lb_17]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[18]}] -filter {direction == output}]
create_generated_clock -name lb_18 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3211.26 [get_clocks lb_18]
set_clock_uncertainty 100 [get_clocks lb_18]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[19]}] -filter {direction == output}]
create_generated_clock -name lb_19 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3293.60 [get_clocks lb_19]
set_clock_uncertainty 100 [get_clocks lb_19]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[20]}] -filter {direction == output}]
create_generated_clock -name lb_20 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3375.94 [get_clocks lb_20]
set_clock_uncertainty 100 [get_clocks lb_20]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[21]}] -filter {direction == output}]
create_generated_clock -name lb_21 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3458.28 [get_clocks lb_21]
set_clock_uncertainty 100 [get_clocks lb_21]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[22]}] -filter {direction == output}]
create_generated_clock -name lb_22 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3540.62 [get_clocks lb_22]
set_clock_uncertainty 100 [get_clocks lb_22]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[23]}] -filter {direction == output}]
create_generated_clock -name lb_23 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3622.96 [get_clocks lb_23]
set_clock_uncertainty 100 [get_clocks lb_23]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[24]}] -filter {direction == output}]
create_generated_clock -name lb_24 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3705.30 [get_clocks lb_24]
set_clock_uncertainty 100 [get_clocks lb_24]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[25]}] -filter {direction == output}]
create_generated_clock -name lb_25 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3787.64 [get_clocks lb_25]
set_clock_uncertainty 100 [get_clocks lb_25]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[26]}] -filter {direction == output}]
create_generated_clock -name lb_26 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3869.98 [get_clocks lb_26]
set_clock_uncertainty 100 [get_clocks lb_26]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[27]}] -filter {direction == output}]
create_generated_clock -name lb_27 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 3952.32 [get_clocks lb_27]
set_clock_uncertainty 100 [get_clocks lb_27]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[28]}] -filter {direction == output}]
create_generated_clock -name lb_28 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 4034.66 [get_clocks lb_28]
set_clock_uncertainty 100 [get_clocks lb_28]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[29]}] -filter {direction == output}]
create_generated_clock -name lb_29 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 4117.00 [get_clocks lb_29]
set_clock_uncertainty 100 [get_clocks lb_29]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[30]}] -filter {direction == output}]
create_generated_clock -name lb_30 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 4199.34 [get_clocks lb_30]
set_clock_uncertainty 100 [get_clocks lb_30]
set _p [get_pins -of_objects [get_nets {clk_lb_buf[31]}] -filter {direction == output}]
create_generated_clock -name lb_31 -source [get_ports clk_spine] -divide_by 1 $_p
set_clock_latency -source 4281.68 [get_clocks lb_31]
set_clock_uncertainty 100 [get_clocks lb_31]

# dont_touch the launch clock nets: repair_design builds a buffer
# TREE for each 32-fanout launch net, and those buffers land along
# the net's path toward the grid edge — some inside the grid macro,
# where detailed placement cannot legalize them (DPL-0036, the
# whole 2026-06-14 night). These nets are modeled as ideal,
# un-treed generated clocks anyway (stagger preserved), so there is
# nothing to buffer. This is what stops the stranding at the root.
set_dont_touch [get_nets {clk_lw_buf[*] clk_lb_buf[*]}]

# Host/GMEM interface — behavioral-controller contract (CHIP_SPEC §6).
set_input_delay  -clock clk 800 [get_ports {rst push_en push_instr[*] gmem_rd_data[*]}]
set_output_delay -clock clk 800 [get_ports {fifo_full idle gmem_rd_addr[*] gmem_wr_en gmem_wr_addr[*] gmem_wr_data[*] gmem_wr_nbytes[*]}]

# Propagate ONLY the physical clocks (clk + the spine, incl. the
# clk_s_tap tree). The generated launch clocks stay ideal-network so
# their modeled source latency is the arrival STA uses.
set_propagated_clock [get_clocks {clk clk_spine}]
