#!/usr/bin/env python3
"""Generate chip_top's constraint.sdc — the chip-level clock contract.

The chip analog of mac_grid/gen_constraints.py. The hard problem (Phase
7d-3, docs/HARDENING.md): the stage-B launch banks are clocked by the
deliberately-late spine taps (clk_lw_v[i] = west tap LAG_W+i, clk_lb_v[j]
= north tap LAG_B+j). A bare spine tap driving a launch group's ~32
registers is the dont_touch spine net AND an un-treed high-fanout net
whose estimate_parasitics RC reads as a −98 ns hold PHANTOM that drowns
post-CTS repair_timing. The real slack underneath is ~1.3 ns.

The fix has two halves:
  * RTL (chip_top.sv): one ptah_clkbuf per launch tap (lw_drv[i].u /
    lb_drv[j].u) isolates a fresh ownable net (clk_lw_buf / clk_lb_buf).
  * SDC (here): each launch net is a NON-propagated GENERATED CLOCK
    carrying the DESIGNED stagger as source latency (δs·(LAG_W+i) west,
    δe·(LAG_B+j) north). Not propagating it makes STA use the contract
    phase instead of the phantom RC — the same move the grid made with
    -source latency on its clk_v ports, adapted to internal taps.

clk_s (stage A, 806 sinks chip-wide) STAYS a real CTS tree (config.mk
CTS_ARGS -clk_nets {clk clk_s_tap}); only the low-fanout per-row/col
stagger taps are modeled. The grid row clocks (clk_row_v = west taps
0..M-1) drive the grid MACRO pins (one load each) and ride the
propagated spine.

NOTE (honesty): not propagating the launch clocks models the launch-net
delay as the designed stagger; if the launch registers route physically
far from their tap the real net is slower than the model. Verify the
post-route launch paths with propagated clocks before any closure
claim — if they are slow, the follow-up is placement-clustering each
launch group at its grid edge (HARDENING.md / STEPS.md).

Run after changing the spine geometry (LAG_W/LAG_B/δs/δe):
    python3 flow/designs/asap7/chip_top/gen_constraints.py
"""

from pathlib import Path

M = N = 32
PERIOD = 4000.0
DS = 85.0          # west spine stagger, ps/tap (ARRAY_SPEC §1)
DE = 82.34         # north spine stagger, ps/tap
LAG_W = 17         # stage-B west launch tap offset (chip_top.sv)
LAG_B = 21         # stage-B B launch tap offset
UNC = 100.0
IO = 800.0         # host/GMEM behavioral-controller budget (CHIP_SPEC §6)

HERE = Path(__file__).parent


def main():
    L = []
    A = L.append
    A("# GENERATED by gen_constraints.py — do not hand-edit.")
    A("# The chip-level clock contract (CHIP_SPEC §1-2, HARDENING.md 7d-3).")
    A("# Units: PICOSECONDS.")
    A("")
    A(f"set clk_period {PERIOD:g}")
    A("")
    A("# Two source clocks: clk (logic, CTS trees it) and clk_spine (the")
    A("# deliberate traveling-clock backbone; clk_s_tap is its CTS-treed")
    A("# stage-A fanout — config.mk CTS_ARGS).")
    A("create_clock -name clk       -period $clk_period [get_ports clk]")
    A("create_clock -name clk_spine -period $clk_period [get_ports clk_spine]")
    A("set_clock_uncertainty 100 [get_clocks clk]")
    A("set_clock_uncertainty 100 [get_clocks clk_spine]")
    A("")
    A("# The spine BACKBONE is deliberate structure — CTS must not balance")
    A("# it, the resizer must not size it (matched by instance path, so the")
    A("# launch tap drivers and CTS buffers stay free; HARDENING ODB-0373).")
    A('set_dont_touch [get_cells -hierarchical -filter "name =~ *u_spine_*"]')
    A('set_dont_touch [get_nets  -hierarchical -filter "name =~ *u_spine_*"]')
    A("")
    A("# ── Stage-B launch clocks: per-tap generated clocks carrying the")
    A("# designed stagger as source latency, NOT propagated (the contract")
    A("# phase replaces the un-treed-net phantom RC). Anchored on each")
    A("# launch buffer's output net driver — hierarchy-robust.")
    gen_clocks = []
    for i in range(M):
        lat = (LAG_W + i) * DS
        nm = f"lw_{i}"
        gen_clocks.append(nm)
        A(f"set _p [get_pins -of_objects [get_nets {{clk_lw_buf[{i}]}}] "
          f"-filter {{direction == output}}]")
        A(f"create_generated_clock -name {nm} -source [get_ports clk_spine] "
          f"-divide_by 1 $_p")
        A(f"set_clock_latency -source {lat:.2f} [get_clocks {nm}]")
        A(f"set_clock_uncertainty {UNC:g} [get_clocks {nm}]")
    for j in range(N):
        lat = (LAG_B + j) * DE
        nm = f"lb_{j}"
        gen_clocks.append(nm)
        A(f"set _p [get_pins -of_objects [get_nets {{clk_lb_buf[{j}]}}] "
          f"-filter {{direction == output}}]")
        A(f"create_generated_clock -name {nm} -source [get_ports clk_spine] "
          f"-divide_by 1 $_p")
        A(f"set_clock_latency -source {lat:.2f} [get_clocks {nm}]")
        A(f"set_clock_uncertainty {UNC:g} [get_clocks {nm}]")
    A("")
    A("# dont_touch the launch clock nets: repair_design builds a buffer")
    A("# TREE for each 32-fanout launch net, and those buffers land along")
    A("# the net's path toward the grid edge — some inside the grid macro,")
    A("# where detailed placement cannot legalize them (DPL-0036, the")
    A("# whole 2026-06-14 night). These nets are modeled as ideal,")
    A("# un-treed generated clocks anyway (stagger preserved), so there is")
    A("# nothing to buffer. This is what stops the stranding at the root.")
    A("set_dont_touch [get_nets {clk_lw_buf[*] clk_lb_buf[*]}]")
    A("")
    A("# Host/GMEM interface — behavioral-controller contract (CHIP_SPEC §6).")
    A(f"set_input_delay  -clock clk {IO:g} "
      "[get_ports {rst push_en push_instr[*] gmem_rd_data[*]}]")
    A(f"set_output_delay -clock clk {IO:g} "
      "[get_ports {fifo_full idle gmem_rd_addr[*] gmem_wr_en gmem_wr_addr[*] "
      "gmem_wr_data[*] gmem_wr_nbytes[*]}]")
    A("")
    A("# Propagate ONLY the physical clocks (clk + the spine, incl. the")
    A("# clk_s_tap tree). The generated launch clocks stay ideal-network so")
    A("# their modeled source latency is the arrival STA uses.")
    A("set_propagated_clock [get_clocks {clk clk_spine}]")
    txt = "\n".join(L) + "\n"
    (HERE / "constraint.sdc").write_text(txt)
    print(f"wrote {HERE/'constraint.sdc'} ({len(L)} lines, "
          f"{len(gen_clocks)} generated launch clocks)")
    print(f"  west lw_0..lw_{M-1}: latency {LAG_W*DS:.0f}..{(LAG_W+M-1)*DS:.0f} ps")
    print(f"  north lb_0..lb_{N-1}: latency {LAG_B*DE:.0f}..{(LAG_B+N-1)*DE:.0f} ps")


if __name__ == "__main__":
    main()
