#!/usr/bin/env python3
"""Generate chip_top's macro placement + io constraints (CHIP_SPEC §3).

Layout (all µm, origin SW):

           ┌────────── north strip (B launch banks + north spine) ───┐
  ┌────────┼─────────────────────────────────────────────────────────┤
  │  west  │                                                         │
  │  strip │              mac_grid macro (fifth GDS)                 │
  │ SRAMs +│              1497.312 × 1535.76, R0                     │
  │ logic +│              north edge = B pins (row 0 at top)         │
  │ spine  │              west edge = per-row clk/data pins          │
  └────────┴─────────────────────────────────────────────────────────┘

The grid macro sits south-east; its west pins face the strip where the
launch banks, spine, SMEM macros and engines live; its north pins face
the strip where the B launch banks live. 16 fakeram7_256x256 (33.25 ×
84.0) stack in one column at the far west — LOAD/fetch logic between
them and the launch region.

Run after any geometry change:
    python3 flow/designs/asap7/chip_top/gen_floorplan.py
Then sync DIE_AREA / CORE_AREA in config.mk with the printed values.
"""

from pathlib import Path

HERE = Path(__file__).parent

# quanta (the 7b-3 track lesson; chip placements snap to these anyway)
QX, QY = 0.432, 2.16

GRID_W, GRID_H = 1497.312, 1535.76
RAM_W, RAM_H = 33.25, 84.0

MARGIN = 2.16          # core-to-die (PDN-0351)
W_STRIP = 220.32       # west strip width (SRAM col + logic + launch).
                       # WIDE DIE (2026-06-15): the clk/clk_spine pins sit
                       # on the far-west die edge (io_constraints below), so
                       # CTS roots the clk_s_tap H-tree in the west. At the
                       # tight 172.8 width the logic strip was too congested
                       # for the legalizer's diamond search to find free
                       # sites near those root buffers → CTS DPL-0036 (5
                       # clk buffers stranded in the x<6.5 sliver). Widening
                       # the strip gives the legalizer reachable whitespace.
                       # This was the documented fix, previously blocked
                       # ONLY by the 7.7 GB RAM wall (DPL swap-thrash); WSL
                       # memory raised to 13 GB makes the wide die fit.
N_STRIP = 64.8         # north strip height (B launch + north spine)
HALO = 2.0             # MACRO_PLACE_HALO around every macro


def snap(v, q):
    return round(round(v / q) * q, 3)


def main():
    grid_x = MARGIN + W_STRIP
    grid_y = MARGIN
    die_w = snap(grid_x + GRID_W + MARGIN, QX)
    die_h = snap(grid_y + GRID_H + N_STRIP + MARGIN, QY)

    L = []
    A = L.append
    A("# GENERATED by gen_floorplan.py — do not hand-edit (CHIP_SPEC §3)")
    A(f"place_macro -macro_name u_mma.u_arr.u_grid "
      f"-location {{{grid_x:.3f} {grid_y:.3f}}} -orientation R0")
    # SRAM column at the far west: copy A banks bottom-up, then copy B.
    # 16 × 84 µm + halos needs ~1.4 mm of the ~1.53 mm core height.
    # Names are BRACED: the ODB keeps Yosys escapes, so the instance
    # name literally contains backslashes — unbraced, TCL consumes them
    # and place_macro finds nothing (MPL-0020; mac_grid pattern).
    ram_x = MARGIN + 4.32
    y = MARGIN + 8.64
    for g in range(8):
        A(f"place_macro -macro_name {{u_smem.bank\\[{g}\\].u_copy_a}} "
          f"-location {{{ram_x:.3f} {snap(y, QY):.3f}}} -orientation R0")
        y += RAM_H + 2 * HALO + 2.16
    for g in range(8):
        A(f"place_macro -macro_name {{u_smem.bank\\[{g}\\].u_copy_b}} "
          f"-location {{{ram_x:.3f} {snap(y, QY):.3f}}} -orientation R0")
        y += RAM_H + 2 * HALO + 2.16
    ram_top = y
    (HERE / "macro_place.tcl").write_text("\n".join(L) + "\n")

    io = []
    B = io.append
    B("# GENERATED by gen_floorplan.py — do not hand-edit")
    B("# clocks + host + gmem all on the west die edge, south of the")
    B("# SRAM column's logic region")
    B(f"set_io_pin_constraint -pin_names {{clk clk_spine rst}} "
      f"-region left:{MARGIN:.2f}-{MARGIN + 40:.2f}")
    B("set_io_pin_constraint -pin_names {push_en push_instr[*] fifo_full idle} "
      f"-region left:{MARGIN + 40:.2f}-{MARGIN + 300:.2f}")
    B("set_io_pin_constraint -pin_names {gmem_rd_addr[*] gmem_rd_data[*]} "
      f"-region left:{MARGIN + 300:.2f}-{MARGIN + 800:.2f}")
    B("set_io_pin_constraint -pin_names {gmem_wr_en gmem_wr_addr[*] "
      "gmem_wr_data[*] gmem_wr_nbytes[*]} "
      f"-region left:{MARGIN + 800:.2f}-{MARGIN + 1100:.2f}")
    (HERE / "io_constraints.tcl").write_text("\n".join(io) + "\n")

    # full precision — %g's 6 significant digits truncated 1674.432 to
    # 1674.43, sliding the core right edge one site short of the grid
    # macro (MPL-0034)
    print(f"DIE_AREA  = 0 0 {die_w:.3f} {die_h:.3f}")
    print(f"CORE_AREA = {MARGIN:.3f} {MARGIN:.3f} "
          f"{snap(die_w - MARGIN, QX):.3f} {snap(die_h - MARGIN, QY):.3f}")
    print(f"grid macro at ({grid_x:.3f}, {grid_y:.3f}); "
          f"SRAM column top {ram_top:.1f} (core height "
          f"{die_h - 2 * MARGIN:.1f})")
    print(f"wrote {HERE/'macro_place.tcl'} + {HERE/'io_constraints.tcl'}")


if __name__ == "__main__":
    main()
