# GENERATED by gen_floorplan.py — do not hand-edit
# clocks + host + gmem all on the west die edge, south of the
# SRAM column's logic region
set_io_pin_constraint -pin_names {clk clk_spine rst} -region left:2.16-42.16
set_io_pin_constraint -pin_names {push_en push_instr[*] fifo_full idle} -region left:42.16-302.16
set_io_pin_constraint -pin_names {gmem_rd_addr[*] gmem_rd_data[*]} -region left:302.16-802.16
set_io_pin_constraint -pin_names {gmem_wr_en gmem_wr_addr[*] gmem_wr_data[*] gmem_wr_nbytes[*]} -region left:802.16-1102.16
