# GENERATED by gen_floorplan.py — do not hand-edit (CHIP_SPEC §3)
place_macro -macro_name u_mma.u_arr.u_grid -location {222.480 2.160} -orientation R0
place_macro -macro_name {u_smem.bank\[0\].u_copy_a} -location {6.480 10.800} -orientation R0
place_macro -macro_name {u_smem.bank\[1\].u_copy_a} -location {6.480 101.520} -orientation R0
place_macro -macro_name {u_smem.bank\[2\].u_copy_a} -location {6.480 190.080} -orientation R0
place_macro -macro_name {u_smem.bank\[3\].u_copy_a} -location {6.480 280.800} -orientation R0
place_macro -macro_name {u_smem.bank\[4\].u_copy_a} -location {6.480 371.520} -orientation R0
place_macro -macro_name {u_smem.bank\[5\].u_copy_a} -location {6.480 462.240} -orientation R0
place_macro -macro_name {u_smem.bank\[6\].u_copy_a} -location {6.480 550.800} -orientation R0
place_macro -macro_name {u_smem.bank\[7\].u_copy_a} -location {6.480 641.520} -orientation R0
place_macro -macro_name {u_smem.bank\[0\].u_copy_b} -location {6.480 732.240} -orientation R0
place_macro -macro_name {u_smem.bank\[1\].u_copy_b} -location {6.480 822.960} -orientation R0
place_macro -macro_name {u_smem.bank\[2\].u_copy_b} -location {6.480 911.520} -orientation R0
place_macro -macro_name {u_smem.bank\[3\].u_copy_b} -location {6.480 1002.240} -orientation R0
place_macro -macro_name {u_smem.bank\[4\].u_copy_b} -location {6.480 1092.960} -orientation R0
place_macro -macro_name {u_smem.bank\[5\].u_copy_b} -location {6.480 1183.680} -orientation R0
place_macro -macro_name {u_smem.bank\[6\].u_copy_b} -location {6.480 1272.240} -orientation R0
place_macro -macro_name {u_smem.bank\[7\].u_copy_b} -location {6.480 1362.960} -orientation R0
