#!/usr/bin/env python3
"""Generate macro_place.tcl + io_constraints.tcl for the 32x32 grid.

Geometry (docs/ARRAY_SPEC.md, TILE_SPEC.md SS1): tile 46.656 x 47.52 um
-- multiples of lcm(site, M1/M3/M5 pitch) in x and lcm(row, M2/M4 pitch)
in y, so place_macro's track snapping is a no-op and zero-gap abutment
is exact in BOTH axes. Row 0 (the B-receiving north row) sits at the
TOP; rows stack south; below row 31 a 10.8 um stdcell strip holds the
drain column mux + register (the only stdcells in the grid).

Checked-in outputs (regenerate after any geometry change):
    python3 flow/designs/asap7/mac_grid/gen_floorplan.py
"""

from pathlib import Path

M = 32                  # rows
N = 32                  # columns
TILE_W = 46.656
TILE_H = 47.52
MARGIN = 2.16           # core-to-die spacing (PDN ring clearance, 7b-3)
STRIP_H = 10.8          # 40 stdcell rows for the south drain strip

X0 = MARGIN
Y0 = MARGIN + STRIP_H                       # bottom of the tile sea
DIE_W = MARGIN + N * TILE_W + MARGIN
DIE_H = MARGIN + STRIP_H + M * TILE_H + MARGIN
CORE = (MARGIN, MARGIN, DIE_W - MARGIN, DIE_H - MARGIN)

HERE = Path(__file__).parent


def row_y(i: int) -> float:
    """Row 0 north (top), row M-1 south (just above the strip)."""
    return Y0 + (M - 1 - i) * TILE_H


def gen_macro_place() -> str:
    out = [
        "# GENERATED by gen_floorplan.py -- do not hand-edit.",
        f"# {M}x{N} mac_tile macros, pitch {TILE_W} x {TILE_H}, zero gap",
        "# in both axes (every coordinate is a multiple of the track",
        "# quanta, so place_macro snapping is a no-op -- MPL-0041).",
        "# Row 0 at the top: B enters its north pins from the die edge.",
    ]
    for i in range(M):
        y = row_y(i)
        for j in range(N):
            x = X0 + j * TILE_W
            out.append(
                f"place_macro -macro_name {{row\\[{i}\\].col\\[{j}\\].u_tile}}"
                f" -location {{{x:.3f} {y:.2f}}} -orientation R0")
    return "\n".join(out) + "\n"


def gen_io_constraints() -> str:
    """Pin regions: every port on the edge that carries it (TILE_SPEC
    SS4) at its row/column's coordinate span."""
    out = [
        "# GENERATED by gen_floorplan.py -- do not hand-edit.",
        "# West: per-row clock/control/A at that row's y span. North: B",
        "# per column. South: the drain strip interface.",
    ]
    SLOT_W = 2
    for i in range(M):
        y1, y2 = row_y(i), row_y(i) + TILE_H
        pins = [f"clk_v[{i}]", f"rst_v[{i}]", f"en_v[{i}]", f"zero_v[{i}]",
                f"row_hit_v[{i}]"]
        pins += [f"slot_v[{i * SLOT_W + b}]" for b in range(SLOT_W)]
        pins += [f"dslot_v[{i * SLOT_W + b}]" for b in range(SLOT_W)]
        pins += [f"a_v[{i * 32 + b}]" for b in range(32)]
        out.append(
            "set_io_pin_constraint -pin_names {%s} -region left:%.2f-%.2f"
            % (" ".join("{%s}" % p for p in pins), y1, y2))
    for j in range(N):
        x1, x2 = X0 + j * TILE_W, X0 + (j + 1) * TILE_W
        pins = [f"b_n_flat[{j * 32 + b}]" for b in range(32)]
        out.append(
            "set_io_pin_constraint -pin_names {%s} -region top:%.3f-%.3f"
            % (" ".join("{%s}" % p for p in pins), x1, x2))
    south = ["clk_s"] + [f"drain_col_sel[{b}]" for b in range(5)] \
        + [f"drain_data[{b}]" for b in range(32)]
    out.append(
        "set_io_pin_constraint -pin_names {%s} -region bottom:*"
        % " ".join("{%s}" % p for p in south))
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    (HERE / "macro_place.tcl").write_text(gen_macro_place())
    (HERE / "io_constraints.tcl").write_text(gen_io_constraints())
    print(f"die  {DIE_W:.3f} x {DIE_H:.2f}")
    print(f"core {CORE[0]} {CORE[1]} {CORE[2]:.3f} {CORE[3]:.2f}")
    print(f"tiles y {Y0} .. {row_y(0) + TILE_H:.2f}  (row 0 top)")
    print("wrote macro_place.tcl, io_constraints.tcl")
