#!/usr/bin/env python3
"""Generate the grid constraint.sdc from the tile's measured arcs.

The 2D traveling-clock contract, per-bit (docs/ARRAY_SPEC.md §1, learned
the hard way in grid attempts 1–2, see HARDENING.md):

Every feedthrough BIT marches at its own consistent per-hop rate (the
tile routes each bit once; the abutted context repeats it). The fast
corner of those rates spans ~31–95 ps/hop — no single stagger or single
io_delay can wave-match a bus with a 3× internal spread over 31 hops.
The row (7b-3) survived because its parent hold repair inserted ~1.9 ns
of pre-delay buffers on the west port nets — a uniform pre-delay that
pushes every downstream arrival behind the clock. The grid can't buffer
between abutted macros, so the pre-delay becomes an explicit PER-BIT
interface contract instead:

  west input s, bit traveling at δ_min(s):  io(s) = base + max(0, (δe − δ_min(s))·(N−1)) + guard
  north B bit b:                            io(b) = base + max(0, (δs − δb_min(b))·(M−1)) + guard  (+ j·δe per column)
  drain capture (clk_s): an EARLY spine tap — latency ≤ min over bits/rows
      of the chain arrival, so every row is hold-positive by construction
      and the multicycle-2 setup budget absorbs all lateness.

δ_min values are the fast corners of the characterised .lib arc tables —
the most conservative (earliest) arrival STA will ever compute, so the
hold contracts hold at every corner; setup uses the multicycle/cushion.
chip_top (7d) implements the pre-delays physically where it has area
(west strip / north channel), exactly as the row already did.

Run after any tile re-characterisation:
    python3 flow/designs/asap7/mac_grid/gen_constraints.py
"""

import re
import statistics
from pathlib import Path

M = N = 32
PERIOD = 4000.0
SRC = 150.0
DS = 85.0          # southward spine stagger (≈ slow-median b arc)
DE = 82.34         # eastward clk arc, measured 7b-3 + clock-table check
IO_BASE = 600.0    # 15% of period
GUARD = 60.0       # hold guard on top of fast-corner pre-delays
UNC = 100.0

REPO = Path(__file__).resolve().parents[4]
LIB = REPO / "flow/results/asap7/mac_grid_mac_tile/base/mac_tile_typ.lib"
HERE = Path(__file__).parent


def arc_mins(lib_text, pairs):
    """(related_base, pin_name) → min over the arc's tables (fast corner)."""
    out = {}
    for blk in re.split(r"\n\s*pin\(", lib_text)[1:]:
        name = blk.split(")")[0].strip('"')
        base = re.sub(r"\[\d+\]", "", name)
        for tm in re.finditer(r"timing\(\)\s*{(.*?)\n\s*}\n", blk, re.S):
            t = tm.group(1)
            rp = re.search(r'related_pin\s*:\s*"([^"]+)"', t)
            if not rp:
                continue
            rbase = re.sub(r"\[\d+\]", "", rp.group(1))
            if (rbase, base) not in pairs:
                continue
            vals = []
            for v in re.findall(r'values\("([^"]+)"\)', t):
                vals += [float(x) for x in v.replace("\\", "").split(",")]
            if vals:
                key = (rbase, name)
                out[key] = min(min(vals), out.get(key, 1e9))
    return out


def main():
    lib = LIB.read_text()
    ft = arc_mins(lib, {("en_in", "en_out"), ("zero_in", "zero_out"),
                        ("slot_in", "slot_out"),
                        ("drain_slot_in", "drain_slot_out"),
                        ("row_hit_in", "row_hit_out"),
                        ("a_in", "a_out"), ("b_in", "b_out"),
                        ("drain_n_in", "drain_s_out"),
                        ("clk_in", "drain_s_out")})

    def dmin(rel, pin):
        return ft[(rel, pin)]

    L = []
    A = L.append
    A("# GENERATED by gen_constraints.py from the characterised tile lib")
    A("# -- do not hand-edit; the per-bit pre-delays ARE the interface")
    A("# contract (ARRAY_SPEC, HARDENING.md grid attempts 1-2).")
    A("# Units: PICOSECONDS.")
    A("")
    A(f"set clk_period {PERIOD:g}")
    A("")
    A("# Per-row traveling clocks: the southward spine (chip_top's job).")
    for i in range(M):
        A(f"create_clock -name clk_{i} -period $clk_period "
          f"[get_ports \"clk_v\\[{i}\\]\"]")
        A(f"set_clock_latency -source {SRC + i * DS:.2f} [get_clocks clk_{i}]")
        A(f"set_clock_uncertainty {UNC:g} [get_clocks clk_{i}]")
    A("")
    # drain capture tap: earliest chain arrival across bits, minus guard.
    # arrival_min(bit) = SRC (row-0 clock) + launch arc + (M-1)*hop_min
    arr = []
    for b in range(32):
        launch = dmin("clk_in", f"drain_s_out[{b}]")
        hop = dmin("drain_n_in", f"drain_s_out[{b}]")
        arr.append(SRC + launch + (M - 1) * hop)
    clk_s_lat = min(arr) - GUARD
    A("# South-strip capture clock: an EARLY spine tap (not the spine end)")
    A(f"# = min per-bit chain arrival {min(arr):.1f} minus guard {GUARD:g} --")
    A("# every row's drain is hold-positive by construction; lateness is")
    A("# absorbed by the settled-bus multicycle below.")
    A("create_clock -name clk_s -period $clk_period [get_ports clk_s]")
    A(f"set_clock_latency -source {clk_s_lat:.2f} [get_clocks clk_s]")
    A(f"set_clock_uncertainty {UNC:g} [get_clocks clk_s]")
    A("")
    A("# West inputs, per row, per signal: pre-delayed so no bit's fast")
    A("# corner can outrun the eastward clock over 31 hops (the row needed")
    A("# ~1.9 ns of physical pre-delay buffers for exactly this; here it")
    A("# is the delivery contract).")
    west = [("en_v", "en_in", "en_out", 1), ("zero_v", "zero_in", "zero_out", 1),
            ("row_hit_v", "row_hit_in", "row_hit_out", 1)]
    for i in range(M):
        for port, rel, out_pin, _ in west:
            d = IO_BASE + max(0.0, (DE - dmin(rel, out_pin)) * (N - 1)) + GUARD
            A(f"set_input_delay -clock clk_{i} {d:.1f} "
              f"[get_ports \"{port}\\[{i}\\]\"]")
        for bnames, rel, outb in (("slot_v", "slot_in", "slot_out"),
                                  ("dslot_v", "drain_slot_in", "drain_slot_out")):
            for k in range(2):
                d = IO_BASE + max(0.0, (DE - dmin(rel, f"{outb}[{k}]")) * (N - 1)) + GUARD
                A(f"set_input_delay -clock clk_{i} {d:.1f} "
                  f"[get_ports \"{bnames}\\[{i * 2 + k}\\]\"]")
        for b in range(32):
            d = IO_BASE + max(0.0, (DE - dmin("a_in", f"a_out[{b}]")) * (N - 1)) + GUARD
            A(f"set_input_delay -clock clk_{i} {d:.1f} "
              f"[get_ports \"a_v\\[{i * 32 + b}\\]\"]")
    A("")
    A("# North B: per-bit pre-delay vs the southward spine + per-column")
    A("# traveling delivery (j*de with row 0's clock, the 7b-3 contract).")
    for j in range(N):
        for b in range(32):
            pre = max(0.0, (DS - dmin("b_in", f"b_out[{b}]")) * (M - 1))
            d = IO_BASE + pre + GUARD + j * DE
            A(f"set_input_delay -clock clk_0 {d:.1f} "
              f"[get_ports \"b_n_flat\\[{j * 32 + b}\\]\"]")
    A("")
    A("# South strip interface.")
    A(f"set_input_delay  -clock clk_s {IO_BASE:g} [get_ports {{drain_col_sel}}]")
    A(f"set_output_delay -clock clk_s {IO_BASE:g} [get_ports {{drain_data}}]")
    A("")
    A("# Settled-bus drain: 2-cycle, RTL-enforced by STORE's row-change")
    A("# settle bubble (store.sv; ARRAY_SPEC SS3). Everything that crosses")
    A("# the tile sea into the drain register goes through row 31's")
    A("# drain_s_out pins; the per-cycle drain_col_sel path does not.")
    A("set chain_pins {}")
    A(f"for {{set j 0}} {{$j < {N}}} {{incr j}} {{")
    A(r'    lappend chain_pins "row\[31\].col\[$j\].u_tile/drain_s_out[*]"')
    A("}")
    A("set_multicycle_path 2 -setup -through [get_pins $chain_pins]")
    A("set_multicycle_path 1 -hold  -through [get_pins $chain_pins]")
    A("")
    A("# Real constants / slow global signals.")
    A("set_false_path -from [get_ports \"rst_v\\[*\\]\"]")
    A("set_false_path -from [get_ports \"drain_n_flat\\[*\\]\"]")
    A("")
    A("# Port drive: the grid runs DONT_BUFFER_PORTS=1 -- port buffers")
    A("# cannot legalize in the abutted macro sea (the only stdcell rows")
    A("# are the south strip, so buffer_ports turned every pin-adjacent")
    A("# port into a ~1.5 mm detour: 8633 real setup violations at CTS,")
    A("# then 5_1 repair_design's 15k rescue buffers died DPL-0036).")
    A("# Unbuffered ports default to ideal zero-slew sources, so model")
    A("# the chip_top drivers explicitly: data from the spine's BUFx4,")
    A("# clocks from a CTS-grade BUFx24 (7d implements both physically).")
    A("set_driving_cell -lib_cell BUFx4_ASAP7_75t_R -pin Y [all_inputs]")
    A("set_driving_cell -lib_cell BUFx24_ASAP7_75t_R -pin Y "
      "[get_ports \"clk_v\\[*\\]\"]")
    A("set_driving_cell -lib_cell BUFx24_ASAP7_75t_R -pin Y "
      "[get_ports clk_s]")
    A("")
    A("# Propagate from the start: pre-CTS repair must see the eastward")
    A("# macro clk arcs (ideal-clock analysis drops the j*de capture")
    A("# credit and reports tens of thousands of phantom setup")
    A("# violations the resizer then burns an hour failing to fix).")
    A("set_propagated_clock [all_clocks]")
    txt = "\n".join(L) + "\n"
    (HERE / "constraint.sdc").write_text(txt)
    stats = {
        "b pre-delay": [IO_BASE + max(0.0, (DS - dmin('b_in', f'b_out[{b}]')) * 31) + GUARD for b in range(32)],
        "a pre-delay": [IO_BASE + max(0.0, (DE - dmin('a_in', f'a_out[{b}]')) * 31) + GUARD for b in range(32)],
    }
    print(f"clk_s latency = {clk_s_lat:.1f} (spine end would be {SRC + M * DS:.0f})")
    for k, v in stats.items():
        print(f"{k}: min={min(v):.0f} median={statistics.median(v):.0f} max={max(v):.0f}")
    print(f"wrote {HERE/'constraint.sdc'} ({len(L)} lines)")


if __name__ == "__main__":
    main()
